version: "3.3"
services:
  app:
    build: .    
    ports:
      - "80:80"
    container_name: myapp
    image: myapp:v1
    restart: always
    networks:
      - my_network
     
networks:
  my_network:
